# Generated by Django 6.0.5 on 2026-05-26 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FMS', '0003_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='arrival_time',
            field=models.CharField(default='10:00 am', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flight',
            name='departure_time',
            field=models.CharField(default='10:00 am', max_length=20),
            preserve_default=False,
        ),
    ]
