# Generated by Django 6.0.5 on 2026-05-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FMS', '0004_flight_arrival_time_flight_departure_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='available_seats',
            field=models.IntegerField(default=50),
        ),
    ]
