# Generated by Django 6.0.5 on 2026-05-29 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FMS', '0005_flight_available_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='travel_date',
            field=models.DateField(null=True),
        ),
    ]
